# Generated by Selenium IDE
import os
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options  

class TestTest():
  def setup_method(self, method):
    chrome_options = Options()  
    chrome_options.add_argument("--headless")  
    self.driver = webdriver.Chrome(chrome_options=chrome_options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self, add_nunit_attachment):
    self.driver.get("https://maroon-chili-27bd3.netlify.app/")    
    print('open the site')
    self.driver.save_screenshot("/test/home.png")
    path = os.path.join(os.path.abspath(os.path.dirname(__file__)), "home.png")
    print(path)
    add_nunit_attachment(path, "peanut butter jelly time")
