# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- master

pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'
    displayName: UI Test - Install Python  
  - task: CmdLine@2
    inputs:
      script: |
        python -m pip install --upgrade pip
        pip install selenium pytest pytest-nunit
        pip install webdriver-manager
    displayName: UI Test - Install Chromedriver   
  - task: CmdLine@2
    inputs:
      script: 'python -m pytest $(pwd)/test/chili-test.py -v --nunit-xml=test-results.xml'
      #script: 'pytest "$(pwd)/test/chili-test.py" --cov my_project --cov-report html'
      #script: 'pytest "$(pwd)/test/chili-test.py" --junitxml=junit/test-results.xml'
    displayName: UI Test - Run UI Test
    continueOnError: true
  - task: CmdLine@2
    inputs:
      script: |
        ls -lrt
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '**/test-results.xml'
    displayName: UI Test - Publish Result   
