trigger:
  branches:
    include:
    - master

variables:
  - name: 'PROJECT_NAME'
    value: 'maroon-chili'

  - name: 'DEPLOYMENT_PLATFORM'
    value: 'aws'

  - name: 'SSG'
    value: 'gatsby'

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage:
  jobs:
  - job: Jekyll
    steps: 
    - task: UseRubyVersion@0
      inputs:
        versionSpec: '>= 2.2 < 2.6'
      displayName: 'Build - Install Ruby'
    - task: CmdLine@2
      displayName: 'Build - Bundle install'
      inputs:
        script: |
          gem install jekyll
          gem install bundler:1.16.6
    - task: CmdLine@2
      displayName: 'Build - Jekyll build'
      inputs:
        script: |
          bundle install --retry=3 --jobs=4
          bundle exec jekyll b
    condition: eq(variables.SSG, 'jekyll')
  - job: Gatsby
    steps: 
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
    - script: |
        npm install -g gatsby-cli
        npm install
      displayName: 'npm install'
    - script: | 
        gatsby build
      displayName: 'gatsby build'      
    condition: eq(variables.SSG, 'gatsby')    
    
    