trigger:
  branches:
    include:
    - master

variables:
  - name: 'PROJECT_NAME'
    value: 'maroon-chili'

  - name: 'DEPLOYMENT_PLATFORM'
    value: 'aws'

  - name: 'SSG'
    value: 'jekyll'

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage:
  jobs:
  - job: 
    steps: 
    - task: UseRubyVersion@0
      inputs:
        versionSpec: '>= 2.2 < 2.6'
      displayName: 'Build - Install Ruby'
    - task: CmdLine@2
      displayName: 'Build - Bundle install'
      inputs:
        script: |
          gem install jekyll
          gem install bundler:1.16.6
    - task: CmdLine@2
      displayName: 'Build - Jekyll build'
      inputs:
        script: |
          bundle install --retry=3 --jobs=4
          bundle exec jekyll b
    condition: eq(variables.SSG, 'jekyll')